
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import sun.security.util.Length;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LinaCostanza
 */
public class mapa extends javax.swing.JFrame {

    /**
     * Creates new form mapa
     */
    public mapa() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        for (int i = 0; i < mapa.length; i++) {
            for (int j = 0; j < mapa[i].length; j++) {
               mapa[i][j]=new javax.swing.JLabel();
               iconos[2] = new ImageIcon(getClass().getResource("/recursos/piso.png"));
                mapa[i][j].setIcon(iconos[2]);
                jPanel2.add(mapa[i][j]);
                
            }
            
            
        }
   
       
        iconos[1] = new ImageIcon(getClass().getResource("/recursos/personaje en el mapa.png"));
        iconos[3]= new ImageIcon(getClass().getResource("/recursos/pared de lava.png"));
        iconos[4]= new ImageIcon(getClass().getResource("/recursos/cofre.png"));
        iconos[5]= new ImageIcon(getClass().getResource("/recursos/boss.png"));
        mapa[0][0].setIcon(iconos[1]);
        
        mapa[0][1].setIcon(iconos[3]);
        mapa[1][1].setIcon(iconos[3]);
        mapa[2][1].setIcon(iconos[3]);
        mapa[3][1].setIcon(iconos[3]);
        mapa[3][2].setIcon(iconos[3]);
        mapa[5][1].setIcon(iconos[3]);
        mapa[6][1].setIcon(iconos[3]);
        mapa[5][2].setIcon(iconos[3]);
        mapa[7][1].setIcon(iconos[3]);
        mapa[7][2].setIcon(iconos[3]);
        mapa[0][3].setIcon(iconos[3]);
        mapa[1][3].setIcon(iconos[3]);
        mapa[1][5].setIcon(iconos[3]);
        mapa[2][5].setIcon(iconos[3]);
        mapa[2][6].setIcon(iconos[3]);
        mapa[3][4].setIcon(iconos[3]);
        mapa[4][4].setIcon(iconos[3]);
        mapa[5][4].setIcon(iconos[3]);
        mapa[7][4].setIcon(iconos[3]);
        mapa[5][5].setIcon(iconos[3]);
        mapa[6][5].setIcon(iconos[3]);
        mapa[7][5].setIcon(iconos[3]);
        mapa[0][7].setIcon(iconos[3]);
        mapa[6][7].setIcon(iconos[3]);
        mapa[7][0].setIcon(iconos[4]);
        mapa[6][2].setIcon(iconos[4]);
        mapa[6][4].setIcon(iconos[4]);
        mapa[7][6].setIcon(iconos[4]);
        mapa[7][7].setIcon(iconos[5]);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 500));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
       int keyPressed = evt.getKeyCode();
       switch(keyPressed){
           case KeyEvent.VK_W:
               if (posx != 0) {
                    if (!(mapa[posx - 1][posy].getIcon() == iconos[3])) {
                        mapa[posx][posy].setIcon(iconos[2]);
                        posx--;
                        mapa[posx][posy].setIcon(iconos[1]);
                    }
                }
                break;
           case KeyEvent.VK_S:
               if (posx != 7) {
                    if (!(mapa[posx + 1][posy].getIcon() == iconos[3])) {
                        mapa[posx][posy].setIcon(iconos[2]);
                        posx++;
                        mapa[posx][posy].setIcon(iconos[1]);
                    }
                }
                break;
           case KeyEvent.VK_A:
                case KeyEvent.VK_LEFT:
                if (posy != 0) {
                    if (!(mapa[posx][posy - 1].getIcon() == iconos[3])) {
                        mapa[posx][posy].setIcon(iconos[2]);
                        posy--;
                        mapa[posx][posy].setIcon(iconos[1]);
                    }
                }
                break;
           case KeyEvent.VK_D:  
               if (posy != 7) {
                    if (!(mapa[posx][posy + 1].getIcon() == iconos[3])) {
                        mapa[posx][posy].setIcon(iconos[2]);
                        posy++;
                        mapa[posx][posy].setIcon(iconos[1]);
                    }
                }
                break;
       }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mapa().setVisible(true);
            }
        });
    }
    
        private final JLabel[][] mapa = new JLabel[8][8];
        
        private final ImageIcon[] iconos = new ImageIcon[6];
        public int posx=0;
        public int posy=0;
       
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
